In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv("C:\\Users\\Sanjay\\Documents\\All working files\\machine-learning\\data\\machine learning data\\diabetes.csv")

In [4]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [6]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [7]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [9]:
corr_matrix = pd.DataFrame(X_scaled).corr()

In [10]:
corr_matrix

,0,1,2,3,4,5,6,7
0,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341
1,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514
2,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528
3,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970
4,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163
5,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242
6,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561
7,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000

In [12]:
eigenvalues, eigenvectors =np.linalg.eigh(corr_matrix)

In [13]:
eigenvalues

array([0.40446205, 0.41981618, 0.68262839, 0.76234439, 0.87552904,
       1.02962987, 1.73121014, 2.09437995])

In [26]:
eigenvectors

array([[-0.11784098, -0.58879003,  0.19359817, -0.47560573,  0.08069115,
         0.01308692,  0.59378583, -0.1284321 ],
       [-0.45035526, -0.06015291,  0.09416176,  0.46632804, -0.40432871,
        -0.46792282,  0.17402908, -0.39308257],
       [ 0.01129554, -0.19211793, -0.6341159 ,  0.32795306,  0.05598649,
         0.53549442,  0.18389207, -0.36000261],
       [-0.5662838 ,  0.28221253,  0.00958944, -0.48786206,  0.03797608,
         0.2376738 , -0.33196534, -0.43982428],
       [ 0.54862138, -0.13200992, -0.27065061, -0.34693481, -0.34994376,
        -0.33670893, -0.25078106, -0.43502617],
       [ 0.34151764, -0.03536644,  0.68537218,  0.25320376,  0.05364595,
         0.36186463, -0.1009598 , -0.45194134],
       [ 0.00825873, -0.08609107, -0.08578409,  0.11981049,  0.8336801 ,
        -0.43318905, -0.122069  , -0.27061144],
       [ 0.21166198,  0.71208542, -0.03335717, -0.10928996,  0.0712006 ,
        -0.07524755,  0.62058853, -0.19802707]])

In [32]:
eigenvalues

array([0.40446205, 0.41981618, 0.68262839, 0.76234439, 0.87552904,
       1.02962987, 1.73121014, 2.09437995])

In [41]:
np.argsort(eigenvalues)[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [57]:
eigenvalues[np.argsort(eigenvalues)[::-1]]/np.sum(eigenvalues[np.argsort(eigenvalues)[::-1]])

array([0.26179749, 0.21640127, 0.12870373, 0.10944113, 0.09529305,
       0.08532855, 0.05247702, 0.05055776])

In [61]:
eigenvectors[:,np.argsort(eigenvalues)[::-1]]

array([[-0.1284321 ,  0.59378583,  0.01308692,  0.08069115, -0.47560573,
         0.19359817, -0.58879003, -0.11784098],
       [-0.39308257,  0.17402908, -0.46792282, -0.40432871,  0.46632804,
         0.09416176, -0.06015291, -0.45035526],
       [-0.36000261,  0.18389207,  0.53549442,  0.05598649,  0.32795306,
        -0.6341159 , -0.19211793,  0.01129554],
       [-0.43982428, -0.33196534,  0.2376738 ,  0.03797608, -0.48786206,
         0.00958944,  0.28221253, -0.5662838 ],
       [-0.43502617, -0.25078106, -0.33670893, -0.34994376, -0.34693481,
        -0.27065061, -0.13200992,  0.54862138],
       [-0.45194134, -0.1009598 ,  0.36186463,  0.05364595,  0.25320376,
         0.68537218, -0.03536644,  0.34151764],
       [-0.27061144, -0.122069  , -0.43318905,  0.8336801 ,  0.11981049,
        -0.08578409, -0.08609107,  0.00825873],
       [-0.19802707,  0.62058853, -0.07524755,  0.0712006 , -0.10928996,
        -0.03335717,  0.71208542,  0.21166198]])

In [68]:
def PCA(X,n_components):
    scaler = StandardScaler() # obj of StandardScaler class
    X_scaled = scaler.fit_transform(X) # standardizing the data
    corr_matrix = pd.DataFrame(X_scaled).corr() # creating corr matrix
    eigenvalues, eigenvectors =np.linalg.eigh(corr_matrix)  # finding eigen values and eigen vectors
    desc_sorted_index = np.argsort(eigenvalues)[::-1] # finding the index for eigenvalues in descending
    sorted_vectors = eigenvectors[:,desc_sorted_index] # sorted vectors according to eigen values
    pca_components = np.dot(X_scaled,eigenvectors[:,np.argsort(eigenvalues)[::-1]][:,:n_components])

    return pca_components

In [69]:
PCA(X,n_components=8)

array([[-1.06850273,  1.23489499, -0.09592984, ...,  0.35718251,
         0.85882133, -0.97430355],
       [ 1.12168331, -0.73385167,  0.71293816, ..., -0.40632934,
         0.75703403, -0.35421454],
       [ 0.39647671,  1.59587594, -1.76067844, ..., -0.04001752,
        -1.15299029, -1.06852795],
       ...,
       [ 0.28347525,  0.09706503,  0.07719194, ..., -0.53826993,
        -0.33556321, -0.2894389 ],
       [ 1.06032431,  0.83706234, -0.42503045, ...,  0.15330712,
         1.18030813,  0.53434386],
       [ 0.83989172, -1.15175485,  1.00917817, ..., -0.15009639,
         0.24523536, -0.51594622]])

In [65]:
X_train, X_test, y_train, y_test = train_test_split(my_X,y,test_size=0.2,random_state=1)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7792207792207793
[[89 10]
 [24 31]]

In [66]:
pca = PCA(n_components=8)
pca_X = pca.fit_transform(X_scaled)
X_train, X_test, y_train, y_test = train_test_split(pca_X,y,test_size=0.2,random_state=1)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7792207792207793
[[89 10]
 [24 31]]

In [60]:
pca.explained_variance_ratio_

array([0.26179749, 0.21640127, 0.12870373, 0.10944113, 0.09529305,
       0.08532855, 0.05247702, 0.05055776])